name: "Pull Request Docs Check"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: sudo apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    - run: sudo pip install -r requirements.txt

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make html"

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: _build/html/

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: _build/latex/moduleor1.pdf

