name: "Pull Request Docs Check"


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    - run: sudo pip install -r requirements.txt

   
    - run: "make latexpdf"
    - run: "make html"

   
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: build/html/

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationPDF
        path: build/latex/moduleor1.pdf

