name: "Pull Request Docs Check"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --deploy --dev

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make html"

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: _build/html/

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: _build/latex/moduleor1.pdf

